#ifndef BLACK_BLASTEROIDS_DISPLAY_H
#define BLACK_BLASTEROIDS_DISPLAY_H

const int FPS = 30;
const int DISPLAY_WIDTH = 800;
const int DISPLAY_HEIGHT = 600;
const int DISPLAY_OFFSET_X = (DISPLAY_WIDTH / 2);
const int DISPLAY_OFFSET_Y = (DISPLAY_HEIGHT / 2);

#endif
